ERROR [2018-05-25 15:50:14,687] (transactions.py:39): 127.0.0.1: division by zero
ERROR [2018-05-25 15:50:51,236] (transactions.py:39): remote_addr - 127.0.0.1: division by zero
ERROR [2018-05-25 15:51:27,809] (transactions.py:39): remote_addr<127.0.0.1> - division by zero
ERROR [2018-05-25 15:53:21,717] (transactions.py:39): remote_addr<127.0.0.1>,params<user111111,1231> - division by zero
ERROR [2018-05-25 15:59:33,050] (transactions.py:214): remote_addr<127.0.0.1> - division by zero
ERROR [2018-05-25 16:19:36,075] (validators.py:48): division by zero
ERROR [2018-05-25 16:20:45,180] (validators.py:48): Traceback (most recent call last):
  File "H:\workspace\UlordOpenApi\ulord\forms\validators.py", line 45, in __call__
    1/0
ZeroDivisionError: division by zero

